name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Publish .NET Core Project
        run: dotnet publish VeterinariaGenesis.Client/VeterinariaGenesis.Client.csproj -c Release -o release --nologo

      - name: Change base-tag in index.html for GitHub Pages
        run: sed -i 's/<base href="\/" \/>/<base href="\/VeterinariaGenesis1\/" \/>/g' release/wwwroot/index.html

      # Forzando el archivo de desbloqueo en la carpeta de salida
      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
          clean: true
          # Esta opción asegura que el archivo .nojekyll se mantenga
          force: true
